### ISSUE TITLE
Error after cloning the project and performing a ./mvnw clean install

### ISSUE THREAD

**Issue by csiegmundt** [shekhargulati/spring-boot-maven-angular-starter#3]
@shekhargulati  I cloned the spring-boot-maven-angular-starter project and when I ran './mvnw clean install' I receive the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project backend: Fatal error compiling: CompilerException: InvocationTargetException: java.nio.file.NotDirectoryException: /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib/modules -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project backend: Fatal error compiling
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)

**Comment by shekhargulati** [comment]
@csiegmundt I have not tested this starter project with JDK 9. Can you try with JDK 8?
