### ISSUE TITLE
frontend should call backend

### ISSUE THREAD

**Issue by dickschoeller** [shekhargulati/spring-boot-maven-angular-starter#8]
Perhaps I am missing something. I can't see the frontend ever actually hitting the backend service.

I would think that a point of a combined application like this would be that the frontend presents data that's from the backend. Getting this set up in a relocatable way is a bit of a nuisance. So, a clear example would be great.

**Comment by shekhargulati** [comment]
Added link to the application that shows the complete example https://github.com/shekhargulati/spring-boot-maven-angular-starter#example-application
